name: Authenticate through GCP and if tagged, deploy to production + publish GH release

on:
  pull_request:
    branches:
      - master
  push:
    tags:
      - '*'

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == 'nipreps/migas-server'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Authenticate and setup SDK
      - id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ SERVICE_ACCOUNT }}
          token_format: 'access_token'
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: Get gcloud information
        run: gcloud info
      # Use provided deployment script
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install hatch
        run: pip install hatch
      - name: Run deployment script
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: ./deploy/gcp/release-gcp.sh ${{ github.ref }}

  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: deploy
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Create GitHub release from annotated tag
        uses: spenserblack/actions-tag-to-release@v1.1.0
        with:
          prerelease: auto
          prerelease-pattern: '*rc*'
